version: "3.9"
services:
  app:
    container_name: fastapi_app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd ..; alembic upgrade head; cd src; uvicorn main:app --host 0.0.0.0'
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - practice
  db:
    container_name: postgres_db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_USER}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "6543:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - practice

networks:
  practice: