"""init tables

Revision ID: ef0ff669d9be
Revises: 
Create Date: 2024-03-17 15:01:31.494055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0ff669d9be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firepower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gun_type', sa.String(), nullable=False),
    sa.Column('shell_count', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.String(), nullable=False),
    sa.Column('penetration', sa.String(), nullable=False),
    sa.Column('shell_type', sa.String(), nullable=False),
    sa.Column('reload', sa.Float(), nullable=False),
    sa.Column('inside_reload', sa.Float(), nullable=False),
    sa.Column('autoreload', sa.String(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('reduction_time', sa.Float(), nullable=False),
    sa.Column('dpm', sa.Integer(), nullable=False),
    sa.Column('elevation_vertical_angles', sa.String(), nullable=False),
    sa.Column('elevation_horizontal_angles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mobility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('specific_power', sa.Float(), nullable=False),
    sa.Column('max_forward_speed', sa.Float(), nullable=False),
    sa.Column('max_backward_speed', sa.Float(), nullable=False),
    sa.Column('rotation_speed', sa.Float(), nullable=False),
    sa.Column('tower_rotation_speed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standing_stealth', sa.String(), nullable=False),
    sa.Column('moving_stealth', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survival',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('hull_armor', sa.String(), nullable=False),
    sa.Column('tower_armor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vision_range', sa.Integer(), nullable=False),
    sa.Column('communication_range', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gun_association_table',
    sa.Column('firepower_id', sa.Integer(), nullable=True),
    sa.Column('gun_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firepower_id'], ['firepower.id'], ),
    sa.ForeignKeyConstraint(['gun_id'], ['gun.id'], )
    )
    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survival_id', sa.Integer(), nullable=False),
    sa.Column('firepower_id', sa.Integer(), nullable=False),
    sa.Column('mobility_id', sa.Integer(), nullable=False),
    sa.Column('vision_id', sa.Integer(), nullable=False),
    sa.Column('stealth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firepower_id'], ['firepower.id'], ),
    sa.ForeignKeyConstraint(['mobility_id'], ['mobility.id'], ),
    sa.ForeignKeyConstraint(['stealth_id'], ['stealth.id'], ),
    sa.ForeignKeyConstraint(['survival_id'], ['survival.id'], ),
    sa.ForeignKeyConstraint(['vision_id'], ['vision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('slug_field', sa.String(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tank')
    op.drop_table('specification')
    op.drop_table('gun_association_table')
    op.drop_table('vision')
    op.drop_table('survival')
    op.drop_table('stealth')
    op.drop_table('mobility')
    op.drop_table('gun')
    op.drop_table('firepower')
    # ### end Alembic commands ###
